[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
