[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['echo "Build complete - Node.js backend ready"']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
